# Generated by Django 5.0.2 on 2024-06-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
