# Generated by Django 3.2.3 on 2024-05-31 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='slugs',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
