# Generated by Django 5.0.2 on 2024-04-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0002_new_alter_shop_friday_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='new_tag',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
