# Generated by Django 5.0.2 on 2024-06-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0002_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='nearest_shop',
        ),
        migrations.AddField(
            model_name='product',
            name='nearest_shop',
            field=models.BooleanField(null=True),
        ),
    ]
