# Generated by Django 3.2.3 on 2024-05-31 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0002_shop_slugs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='slugs',
            new_name='slug',
        ),
    ]
