# Generated by Django 5.0.2 on 2024-05-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0003_shop_new_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
        migrations.AlterField(
            model_name='shop',
            name='new_tag',
            field=models.BooleanField(blank=True),
        ),
    ]
