# Generated by Django 5.0.2 on 2024-06-06 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0003_remove_shop_nearest_shop_product_nearest_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='nearest_shop',
            new_name='hot_trend',
        ),
    ]
