# Generated by Django 3.2.3 on 2024-05-31 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0003_rename_slugs_shop_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='description',
        ),
    ]
