# Generated by Django 5.0.2 on 2024-05-01 11:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0004_delete_new_alter_shop_new_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
