# Generated by Django 5.0.3 on 2024-10-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0004_rename_nearest_shop_product_hot_trend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('support', models.EmailField(max_length=254)),
            ],
        ),
    ]
