# Generated by Django 5.0.2 on 2024-05-01 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0005_shop_created_at_shop_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='new_tag',
        ),
    ]
