# Generated by Django 3.2.3 on 2024-05-31 22:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0005_alter_product_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_bio',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
