# Generated by Django 5.0.3 on 2024-10-01 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0005_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Location',
        ),
    ]
