# Generated by Django 5.0.2 on 2024-05-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0006_remove_shop_new_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100, verbose_name='Shop Name')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('monday_start_time', models.TimeField(auto_now_add=True, null=True)),
                ('monday_end_time', models.TimeField(auto_now_add=True, null=True)),
                ('tuesday_start_time', models.TimeField(auto_now_add=True, null=True)),
                ('tuesday_end_time', models.TimeField(auto_now_add=True, null=True)),
                ('wednesday_start_time', models.TimeField(auto_now_add=True, null=True)),
                ('wednesday_end_time', models.TimeField(auto_now_add=True, null=True)),
                ('thursday_start_time', models.TimeField(auto_now_add=True, null=True)),
                ('thursday_end_time', models.TimeField(auto_now_add=True, null=True)),
                ('friday_start_time', models.TimeField(auto_now_add=True, null=True)),
                ('friday_end_time', models.TimeField(auto_now_add=True, null=True)),
                ('saturday_start_time', models.TimeField(auto_now_add=True, null=True)),
                ('saturday_end_time', models.TimeField(auto_now_add=True, null=True)),
                ('sunday_start_time', models.TimeField(auto_now_add=True, null=True)),
                ('sunday_end_time', models.TimeField(auto_now_add=True, null=True)),
                ('product', models.CharField(max_length=100)),
                ('product_image1', models.ImageField(null=True, upload_to='')),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.TextField(max_length=50)),
            ],
        ),
    ]
