# Generated by Django 5.0.2 on 2024-05-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0007_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='shop_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
