# Generated by Django 5.0.2 on 2024-05-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0008_detail_description_detail_shop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
