# Generated by Django 5.0.2 on 2024-05-08 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0009_alter_shop_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='shop_image',
        ),
    ]
