# Generated by Django 5.0.2 on 2024-05-08 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0010_remove_detail_shop_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='address',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='description',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='shop_name',
        ),
    ]
