# Generated by Django 5.0.2 on 2024-05-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0011_remove_detail_address_remove_detail_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='product',
        ),
    ]
