# Generated by Django 5.0.2 on 2024-05-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0013_shop_shop_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='shop_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Shop Name'),
        ),
    ]
