# Generated by Django 5.0.2 on 2024-05-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0014_detail_shop_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='shop_name',
            new_name='name_of_shop',
        ),
        migrations.AlterField(
            model_name='detail',
            name='price',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
