# Generated by Django 5.0.2 on 2024-05-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0015_rename_shop_name_detail_name_of_shop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='shop_product',
        ),
        migrations.AddField(
            model_name='shop',
            name='price',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shop',
            name='product_image1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='shop',
            name='product_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
