# Generated by Django 5.0.2 on 2024-05-08 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0016_remove_shop_shop_product_shop_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(blank=True, max_length=100, verbose_name='Shop Name')),
                ('product_image1', models.ImageField(null=True, upload_to='')),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.CharField(blank=True, max_length=50)),
                ('monday_start_time', models.TimeField(auto_now_add=True, null=True)),
                ('monday_end_time', models.TimeField(auto_now_add=True, null=True)),
                ('tuesday_start_time', models.TimeField(auto_now_add=True, null=True)),
                ('tuesday_end_time', models.TimeField(auto_now_add=True, null=True)),
                ('wednesday_start_time', models.TimeField(auto_now_add=True, null=True)),
                ('wednesday_end_time', models.TimeField(auto_now_add=True, null=True)),
                ('thursday_start_time', models.TimeField(auto_now_add=True, null=True)),
                ('thursday_end_time', models.TimeField(auto_now_add=True, null=True)),
                ('friday_start_time', models.TimeField(auto_now_add=True, null=True)),
                ('friday_end_time', models.TimeField(auto_now_add=True, null=True)),
                ('saturday_start_time', models.TimeField(auto_now_add=True, null=True)),
                ('saturday_end_time', models.TimeField(auto_now_add=True, null=True)),
                ('sunday_start_time', models.TimeField(auto_now_add=True, null=True)),
                ('sunday_end_time', models.TimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='shop',
            name='price',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='product_image1',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='product_name',
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='walletapp.detail'),
        ),
    ]
