# Generated by Django 5.0.2 on 2024-05-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0017_detail_remove_shop_price_remove_shop_product_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
