# Generated by Django 5.0.2 on 2024-05-08 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0020_shop_shop_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='shop_product',
        ),
    ]
