# Generated by Django 5.0.2 on 2024-05-08 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0021_remove_shop_shop_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(blank=True, max_length=100)),
                ('product_image1', models.ImageField(null=True, upload_to='')),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('monday_start_time', models.TimeField(auto_now_add=True, null=True)),
                ('monday_end_time', models.TimeField(auto_now_add=True, null=True)),
                ('tuesday_start_time', models.TimeField(auto_now_add=True, null=True)),
                ('tuesday_end_time', models.TimeField(auto_now_add=True, null=True)),
                ('wednesday_start_time', models.TimeField(auto_now_add=True, null=True)),
                ('wednesday_end_time', models.TimeField(auto_now_add=True, null=True)),
                ('thursday_start_time', models.TimeField(auto_now_add=True, null=True)),
                ('thursday_end_time', models.TimeField(auto_now_add=True, null=True)),
                ('friday_start_time', models.TimeField(auto_now_add=True, null=True)),
                ('friday_end_time', models.TimeField(auto_now_add=True, null=True)),
                ('saturday_start_time', models.TimeField(auto_now_add=True, null=True)),
                ('saturday_end_time', models.TimeField(auto_now_add=True, null=True)),
                ('sunday_start_time', models.TimeField(auto_now_add=True, null=True)),
                ('sunday_end_time', models.TimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='walletapp.categories')),
            ],
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
