# Generated by Django 5.0.2 on 2024-05-08 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0022_vendor_delete_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='walletapp.vendor'),
        ),
    ]
