# Generated by Django 5.0.2 on 2024-05-28 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0023_shop_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='vendor',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image1', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('product_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='walletapp.categories')),
                ('shop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walletapp.shop')),
            ],
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
